import type { Prisma } from "@prisma/client";
import { NextResponse } from "next/server";
import { AuthError, requireUser } from "@/lib/auth";
import { generateListingDraft } from "@/lib/ai";
import { prisma } from "@/lib/db";
import { researchProductFromUrl } from "@/lib/research";
import { rateLimit } from "@/lib/rate-limit";
import { urlImportSchema } from "@/lib/validators";
export const runtime = "nodejs";
export async function POST(request: Request) { try { const user = await requireUser(); const limited = await rateLimit({ key: `import:${user.id}`, limit: 60, windowSeconds: 3600 }); if (!limited.allowed) return NextResponse.json({ error: "URL import rate limit reached." }, { status: 429 }); const body = await request.json().catch(() => null); const parsed = urlImportSchema.safeParse(body); if (!parsed.success) return NextResponse.json({ error: "Invalid import URL." }, { status: 400 }); const research = await researchProductFromUrl(parsed.data.url); const draft = await generateListingDraft({ price: parsed.data.price, rawNotes: [parsed.data.rawNotes, research.sourceDescription].filter(Boolean).join("\n\n"), brandVoice: parsed.data.brandVoice, research }); const product = await prisma.product.create({ data: { userId: user.id, sourceUrl: parsed.data.url, price: parsed.data.price, rawNotes: parsed.data.rawNotes, brandVoice: parsed.data.brandVoice, name: draft.productName, category: draft.category, commonMarketName: draft.commonMarketName, seoTitle: draft.seoTitle, shortDescription: draft.shortDescription, longDescription: draft.longDescription, bulletFeatures: draft.bulletFeatures, specifications: draft.specifications as Prisma.InputJsonValue, tags: draft.tags, seoKeywords: draft.seoKeywords, competitorNotes: draft.competitorDescriptions as Prisma.InputJsonValue, metaDescription: draft.metaDescription, suggestedCategory: draft.suggestedCategory, confidence: draft.confidence, aiInputs: research as unknown as Prisma.InputJsonValue, aiOutput: draft as unknown as Prisma.InputJsonValue, generatedAt: new Date(), status: "READY" } }); return NextResponse.json({ product, draft, research }, { status: 201 }); } catch (error) { if (error instanceof AuthError) return NextResponse.json({ error: error.message }, { status: 401 }); const message = error instanceof Error ? error.message : "Unable to import URL."; return NextResponse.json({ error: message }, { status: 400 }); } }
