import type { Prisma } from "@prisma/client";
import { NextResponse } from "next/server";
import { AuthError, requireUser } from "@/lib/auth";
import { generateListingDraft } from "@/lib/ai";
import { prisma } from "@/lib/db";
import { enqueueListingGeneration } from "@/lib/queue";
import { rateLimit } from "@/lib/rate-limit";
import { aiGenerateSchema } from "@/lib/validators";
export const runtime = "nodejs";
export async function POST(request: Request) { try { const user = await requireUser(); const limited = await rateLimit({ key: `ai:${user.id}`, limit: 40, windowSeconds: 3600 }); if (!limited.allowed) return NextResponse.json({ error: "AI generation rate limit reached." }, { status: 429 }); const body = await request.json().catch(() => null); const parsed = aiGenerateSchema.safeParse(body); if (!parsed.success) return NextResponse.json({ error: "Invalid generation payload." }, { status: 400 }); const product = parsed.data.productId ? await prisma.product.findFirst({ where: { id: parsed.data.productId, userId: user.id } }) : await prisma.product.create({ data: { userId: user.id, imageUrl: parsed.data.imageUrl, sourceUrl: parsed.data.sourceUrl, price: parsed.data.price, currency: parsed.data.currency, rawNotes: parsed.data.rawNotes, brandVoice: parsed.data.brandVoice, status: parsed.data.batchMode ? "PROCESSING" : "DRAFT" } }); if (!product) return NextResponse.json({ error: "Product not found." }, { status: 404 }); if (parsed.data.productId) await prisma.product.update({ where: { id: product.id }, data: { status: "PROCESSING" } }); if (parsed.data.batchMode) { const job = await enqueueListingGeneration({ productId: product.id, userId: user.id, imageUrl: parsed.data.imageUrl, price: parsed.data.price, rawNotes: parsed.data.rawNotes, brandVoice: parsed.data.brandVoice }); return NextResponse.json({ product, job }); } const draft = await generateListingDraft({ imageUrl: parsed.data.imageUrl, price: parsed.data.price, rawNotes: parsed.data.rawNotes, brandVoice: parsed.data.brandVoice }); const updated = await prisma.product.update({ where: { id: product.id }, data: { name: draft.productName, category: draft.category, commonMarketName: draft.commonMarketName, seoTitle: draft.seoTitle, shortDescription: draft.shortDescription, longDescription: draft.longDescription, bulletFeatures: draft.bulletFeatures, specifications: draft.specifications as Prisma.InputJsonValue, tags: draft.tags, seoKeywords: draft.seoKeywords, competitorNotes: draft.competitorDescriptions as Prisma.InputJsonValue, metaDescription: draft.metaDescription, suggestedCategory: draft.suggestedCategory, confidence: draft.confidence, aiOutput: draft as unknown as Prisma.InputJsonValue, generatedAt: new Date(), status: "READY" } }); return NextResponse.json({ product: updated, draft }); } catch (error) { if (error instanceof AuthError) return NextResponse.json({ error: error.message }, { status: 401 }); throw error; } }
