"use client";

import { CheckCircle2, FileImage, Loader2, UploadCloud, Wand2 } from "lucide-react";
import { useRef, useState } from "react";
import { Button, Card, CardContent, CardHeader, CardTitle, Progress } from "@/components/ui";

type Item = { id: string; name: string; size: number; progress: number; status: "DRAFT" | "PROCESSING" | "READY" };
export function BulkUploadClient() {
  const inputRef = useRef<HTMLInputElement>(null);
  const [items, setItems] = useState<Item[]>([{ id: "seed-1", name: "satin-pillowcase.webp", size: 1820000, progress: 100, status: "READY" }, { id: "seed-2", name: "usb-c-hub.jpg", size: 2240000, progress: 66, status: "PROCESSING" }]);
  function add(files: FileList | File[]) { setItems((current) => [...Array.from(files).map((f) => ({ id: crypto.randomUUID(), name: f.name, size: f.size, progress: 0, status: "DRAFT" as const })), ...current]); }
  function process() { setItems((current) => current.map((i) => i.status === "READY" ? i : { ...i, status: "PROCESSING", progress: Math.max(i.progress, 12) })); const interval = window.setInterval(() => setItems((current) => { const updated = current.map((i) => { if (i.status === "READY") return i; const progress = Math.min(100, i.progress + Math.ceil(Math.random() * 16)); return { ...i, progress, status: progress >= 100 ? "READY" : "PROCESSING" } as Item; }); if (updated.every((i) => i.status === "READY")) window.clearInterval(interval); return updated; }), 520); }
  const ready = items.filter((i) => i.status === "READY").length;
  return <div className="grid gap-5 xl:grid-cols-[0.9fr_1.1fr]"><Card><CardHeader><CardTitle>Batch intake</CardTitle></CardHeader><CardContent className="space-y-4"><button type="button" className="flex min-h-80 w-full items-center justify-center rounded-lg border border-dashed bg-muted/45 hover:border-primary hover:bg-primary/5" onClick={() => inputRef.current?.click()} onDragOver={(e) => e.preventDefault()} onDrop={(e) => { e.preventDefault(); add(e.dataTransfer.files); }}><span className="flex flex-col items-center gap-3 text-center"><span className="flex h-14 w-14 items-center justify-center rounded-md bg-background shadow-sm"><UploadCloud className="h-6 w-6 text-primary" /></span><span><span className="block text-sm font-medium">Drop multiple product images</span><span className="block text-xs text-muted-foreground">Batch processing keeps status per image</span></span></span></button><input ref={inputRef} type="file" accept="image/*" multiple className="hidden" onChange={(e) => e.target.files && add(e.target.files)} /><Button className="w-full" size="lg" disabled={!items.length} onClick={process}><Wand2 className="h-4 w-4" />Process batch</Button></CardContent></Card><Card><CardHeader className="flex flex-row items-center justify-between"><div><CardTitle>Processing queue</CardTitle><p className="mt-1 text-sm text-muted-foreground">{ready} of {items.length} listings ready</p></div><span className="rounded-md bg-primary/10 px-3 py-1 text-sm font-medium text-primary">{items.length} items</span></CardHeader><CardContent className="space-y-3">{items.map((item) => <div key={item.id} className="rounded-lg border p-4"><div className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-md bg-muted"><FileImage className="h-5 w-5 text-primary" /></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{item.name}</p><p className="text-xs text-muted-foreground">{(item.size / 1000000).toFixed(1)} MB</p></div>{item.status === "READY" ? <CheckCircle2 className="h-5 w-5 text-emerald-500" /> : item.status === "PROCESSING" ? <Loader2 className="h-5 w-5 animate-spin text-primary" /> : <span className="h-5 w-5 rounded-full border" />}</div><Progress value={item.progress} className="mt-4" /></div>)}</CardContent></Card></div>;
}
