"use client";

import { Download, Edit3, MoreHorizontal, Send } from "lucide-react";
import { useMemo, useState } from "react";
import { Badge, Button, Card, Progress } from "@/components/ui";
import { demoProducts } from "@/lib/constants";
import { formatCurrency } from "@/lib/utils";

function StatusBadge({ status }: { status: string }) { const variant = status === "PROCESSING" ? "warning" : status === "FAILED" ? "danger" : status === "DRAFT" ? "secondary" : "success"; return <Badge variant={variant as never}>{status[0] + status.slice(1).toLowerCase()}</Badge>; }

export function ListingsTable() {
  const [selected, setSelected] = useState<string[]>(["prod_001", "prod_003"]);
  const csv = useMemo(() => [["Handle", "Title", "Variant Price", "Tags", "Status"], ...demoProducts.filter((p) => selected.includes(p.id)).map((p) => [p.name.toLowerCase().replace(/[^a-z0-9]+/g, "-"), p.name, p.price, p.category, p.status.toLowerCase()])].map((row) => row.map((cell) => `"${cell}"`).join(",")).join("\n"), [selected]);
  function toggle(id: string) { setSelected((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]); }
  function downloadCsv() { const blob = new Blob([csv], { type: "text/csv;charset=utf-8" }); const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = "listify-ai-shopify-export.csv"; a.click(); URL.revokeObjectURL(url); }
  return <Card className="overflow-hidden"><div className="flex flex-col gap-3 border-b p-4 md:flex-row md:items-center md:justify-between"><div><p className="text-sm font-medium">{selected.length} selected</p><p className="text-xs text-muted-foreground">Review, export, or publish products in bulk</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={downloadCsv} disabled={!selected.length}><Download className="h-4 w-4" />Export CSV</Button><Button disabled={!selected.length}><Send className="h-4 w-4" />Publish</Button></div></div><div className="overflow-x-auto"><table className="w-full min-w-[860px] text-left text-sm"><thead className="bg-muted/60 text-xs uppercase tracking-[0.16em] text-muted-foreground"><tr><th className="w-12 px-4 py-3" /><th className="px-4 py-3">Product</th><th className="px-4 py-3">Category</th><th className="px-4 py-3">Price</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Confidence</th><th className="px-4 py-3">Updated</th><th className="px-4 py-3" /></tr></thead><tbody className="divide-y">{demoProducts.map((product) => <tr key={product.id} className="hover:bg-muted/35"><td className="px-4 py-4"><input aria-label={`Select ${product.name}`} type="checkbox" checked={selected.includes(product.id)} onChange={() => toggle(product.id)} className="h-4 w-4 rounded border-input" /></td><td className="px-4 py-4"><div className="flex items-center gap-3"><img src={product.imageUrl} alt="" className="h-12 w-12 rounded-md object-cover" /><div><p className="font-medium">{product.name}</p><p className="text-xs text-muted-foreground">{product.id}</p></div></div></td><td className="px-4 py-4 text-muted-foreground">{product.category}</td><td className="px-4 py-4">{formatCurrency(product.price)}</td><td className="px-4 py-4"><StatusBadge status={product.status} /></td><td className="px-4 py-4"><div className="flex w-32 items-center gap-2"><Progress value={product.confidence} /><span className="w-9 text-xs text-muted-foreground">{product.confidence}%</span></div></td><td className="px-4 py-4 text-muted-foreground">{product.updatedAt}</td><td className="px-4 py-4"><div className="flex justify-end gap-1"><Button aria-label="Edit" size="icon" variant="ghost"><Edit3 className="h-4 w-4" /></Button><Button aria-label="More" size="icon" variant="ghost"><MoreHorizontal className="h-4 w-4" /></Button></div></td></tr>)}</tbody></table></div></Card>;
}
