import Link from "next/link";
import { ArrowUpRight, Plus } from "lucide-react";
import { AppShell, PageHeading } from "@/components/app-shell";
import { Badge, Button, buttonVariants, Card, CardContent, CardHeader, CardTitle } from "@/components/ui";
import { dashboardStats, demoProducts } from "@/lib/constants";
import { cn } from "@/lib/utils";

export default function DashboardPage() {
  const bars = [54, 72, 64, 92, 78, 46, 69];
  return <AppShell><PageHeading eyebrow="Overview" title="Listing automation dashboard" description="Monitor generation volume, product status, AI confidence, and Shopify publishing from one workspace." actions={<><Button variant="outline">Import URL</Button><Link href="/generator" className={cn(buttonVariants(), "inline-flex items-center gap-2")}><Plus className="h-4 w-4" />New listing</Link></>} /><div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-4">{dashboardStats.map((stat) => { const Icon = stat.icon; return <Card key={stat.label}><CardContent className="p-5"><div className="flex items-center justify-between"><span className="text-sm text-muted-foreground">{stat.label}</span><span className="flex h-9 w-9 items-center justify-center rounded-md bg-primary/10 text-primary"><Icon className="h-4 w-4" /></span></div><div className="mt-5 flex items-end justify-between gap-4"><p className="text-3xl font-semibold">{stat.value}</p><p className="rounded-md bg-emerald-500/10 px-2 py-1 text-xs font-medium text-emerald-700">{stat.change}</p></div></CardContent></Card>; })}</div><div className="mt-5 grid gap-5 xl:grid-cols-[1.6fr_1fr]"><Card><CardHeader><CardTitle>AI generation volume</CardTitle></CardHeader><CardContent><div className="flex h-72 items-end gap-3">{bars.map((value, i) => <div key={i} className="flex flex-1 flex-col items-center gap-3"><div className="flex h-56 w-full items-end rounded-md bg-muted"><div className="w-full rounded-md bg-primary" style={{ height: `${value}%` }} /></div><span className="text-xs text-muted-foreground">{["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"][i]}</span></div>)}</div></CardContent></Card><Card><CardHeader><CardTitle>Recent listings</CardTitle></CardHeader><CardContent className="space-y-3">{demoProducts.slice(0, 4).map((p) => <div key={p.id} className="flex items-center gap-3 rounded-lg border p-3"><img src={p.imageUrl} alt="" className="h-12 w-12 rounded-md object-cover" /><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{p.name}</p><p className="text-xs text-muted-foreground">{p.category}</p></div><Badge variant={p.status === "PROCESSING" ? "warning" : "success"}>{p.status}</Badge></div>)}<Link href="/listings" className="flex items-center gap-1 text-sm font-medium text-primary">View all<ArrowUpRight className="h-4 w-4" /></Link></CardContent></Card></div></AppShell>;
}
